name: home_in_order
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+10

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  micro_core:
    path: packages/micro_core
  micro_dependencies:
    path: packages/micro_dependencies

dev_dependencies:
  flutter_lints: ^2.0.2
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - shorebird.yaml

  fonts:
    - family: Urbanist
      fonts:
        - asset: assets/fonts/urbanist/Urbanist-Light.otf
        - asset: assets/fonts/urbanist/Urbanist-Regular.otf
        - asset: assets/fonts/urbanist/Urbanist-Bold.otf
          weight: 700
