name: micro_auth
ndescription: A new Flutter package project.
version: 0.0.1
publish_to: 'none'

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  latlong2: ^0.9.0
  micro_dependencies:
    path: '../micro_dependencies'
  micro_design_system:
    path: '../micro_design_system'
  micro_core:
    path: '../micro_core'
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

